version: 0.2


phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Running tests...
  build:
    commands:
      - echo Building application...
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - '**/*'
  base-directory: 'dist' # Assuming your build output is in a 'dist' directory